// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//nolint
package grpctl

import (
	"fmt"
	"os"
	"strings"

	"github.com/brehv/r"
	"github.com/joshcarp/grpctl/internal/descriptors"
	"github.com/spf13/cobra"
)

func GetServiceCommand(config Config) *cobra.Command {
	var err error
	rootCmd := &cobra.Command{
		Use:   strings.ToLower("Service"),
		Short: "configure Service",
		Run:   nil,
	}
	something := DefaultService()
	cobra.CheckErr(err)
	m, err := descriptors.NewInterfaceDataValue(something)
	cobra.CheckErr(err)
	get := &cobra.Command{
		Use:   "get",
		Short: "get a Service",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			user, err := config.GetService(args[0])
			cobra.CheckErr(err)
			fmt.Println(user)
		},
	}
	add := &cobra.Command{
		Use:   "add",
		Short: "add a Service",
		Run: func(cmd *cobra.Command, args []string) {
			var ok bool
			for key, val := range m {
				somthingval := r.R(&something, key, val.Value)
				something, ok = somthingval.(Service)
				if !ok {
					cobra.CompError("Error updating Service: this shouldn't happen")
					os.Exit(1)
				}
			}
			config, err = config.AddService(something)
			cobra.CheckErr(err)
			fmt.Println(config)
			cobra.CheckErr(config.Save())
		},
	}
	del := &cobra.Command{
		Use:   "delete",
		Short: "delete a Service",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			config, err = config.DeleteService(args[0])
			cobra.CheckErr(err)
			cobra.CheckErr(config.Save())
		},
	}
	update := &cobra.Command{
		Use:   "update",
		Short: "update a Service",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			v, ok := m["Name"]
			if !ok {
				cobra.CompError("Name not found in Service: this shouldn't happen")
				os.Exit(1)
			}
			something, err := config.GetService(v.String())
			cobra.CheckErr(err)
			for key, val := range m {
				somthingval := r.R(&something, key, val.Value)
				something, ok = somthingval.(Service)
				if !ok {
					cobra.CompError("Error updating Service: this shouldn't happen")
					os.Exit(1)
				}
			}
			config, err = config.UpdateService(something)
			cobra.CheckErr(err)
			cobra.CheckErr(config.Save())
		},
	}
	list := &cobra.Command{
		Use:   "list",
		Short: "list Services",
		Run: func(cmd *cobra.Command, args []string) {
			for _, val := range config.ListService() {
				fmt.Println(val.Name)
			}
		},
	}
	for key, val := range m {
		update.Flags().Var(val, key, "")
		update.RegisterFlagCompletionFunc(key, func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{fmt.Sprintf("%v", m[key])}, cobra.ShellCompDirectiveDefault
		})
	}
	rootCmd.AddCommand(get)
	rootCmd.AddCommand(add)
	rootCmd.AddCommand(update)
	rootCmd.AddCommand(del)
	rootCmd.AddCommand(list)
	return rootCmd
}

func (c Config) GetService(name string) (Service, error) {
	for _, e := range c.Services {
		if e.Name == name {
			return e, nil
		}
	}
	return Service{}, NotFoundError
}

func (c Config) AddService(s Service) (Config, error) {
	for _, e := range c.Services {
		if e.Name == s.Name {
			return Config{}, NotFoundError
		}
	}
	c.Services = append(c.Services, s)
	return c, nil
}

func (c Config) DeleteService(name string) (Config, error) {
	for i, e := range c.Services {
		if e.Name == name {
			c.Services = append(c.Services[:i], c.Services[i+1:]...)
			return c, nil
		}
	}
	return c, NotFoundError
}

func (c Config) UpdateService(s Service) (Config, error) {
	for i, e := range c.Services {
		if e.Name == s.Name {
			c.Services[i] = s
			return c, NotFoundError
		}
	}
	return c, NotFoundError
}

func (c Config) ListService() []Service {
	return c.Services
}
