// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//nolint
package grpctl

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/joshcarp/grpctl/internal/descriptors"
	"github.com/spf13/cobra"
)

func GetEnvironmentCommand(config Service) *cobra.Command {
	var err error
	rootCmd := &cobra.Command{
		Use:   strings.ToLower("Environment"),
		Short: "configure Environment",
		Run:   nil,
	}
	something := DefaultEnvironment()
	cobra.CheckErr(err)
	defaultVals, err := descriptors.NewInterfaceDataValue(something)
	flagstorer := make(descriptors.DataMap)
	cobra.CheckErr(err)
	get := &cobra.Command{
		Use:   "get",
		Short: "get a Environment",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			user, err := config.GetEnvironment(args[0])
			cobra.CheckErr(err)
			fmt.Println(user)
		},
	}
	add := &cobra.Command{
		Use:   "add",
		Short: "add a Environment",
		Run: func(cmd *cobra.Command, args []string) {
			toJson, err := flagstorer.ToJson()
			cobra.CheckErr(err)
			cobra.CheckErr(json.Unmarshal(toJson, &something))
			config, err = config.AddEnvironment(something)
			cobra.CheckErr(err)
			fmt.Println(config)
			cobra.CheckErr(config.Save())
		},
	}
	del := &cobra.Command{
		Use:   "delete",
		Short: "delete a Environment",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			config, err = config.DeleteEnvironment(args[0])
			cobra.CheckErr(err)
			cobra.CheckErr(config.Save())
		},
	}
	update := &cobra.Command{
		Use:   "update",
		Short: "update a Environment",
		Run: func(cmd *cobra.Command, args []string) {
			src := flagstorer.ToInterfaceMap()
			cobra.CheckErr(err)
			v, ok := flagstorer["name"]
			if !ok {
				cobra.CheckErr(InvalidArg)
			}
			context, err := config.GetEnvironment(v.String())
			dst, err := descriptors.ToInterfaceMap(context)
			cobra.CheckErr(err)
			allmap := descriptors.MergeInterfaceMaps(dst, src)
			cobra.CheckErr(descriptors.MapInterfaceToObject(&context, allmap))
			newcfg, err := config.UpdateEnvironment(context)
			cobra.CheckErr(err)
			cobra.CheckErr(newcfg.Save())
		},
	}
	list := &cobra.Command{
		Use:   "list",
		Short: "list all Environments",
		Run: func(cmd *cobra.Command, args []string) {
			for _, val := range config.ListEnvironment() {
				fmt.Println(val.Name)
			}
		},
	}
	for key, val := range defaultVals {
		flagstorer[key] = &descriptors.DataValue{Value: val.Value, Empty: true}
		update.Flags().Var(flagstorer[key], key, "")
		update.RegisterFlagCompletionFunc(key, func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{fmt.Sprintf("%v", val)}, cobra.ShellCompDirectiveDefault
		})
		add.Flags().Var(flagstorer[key], key, "")
		add.RegisterFlagCompletionFunc(key, func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{fmt.Sprintf("%v", val)}, cobra.ShellCompDirectiveDefault
		})
	}
	rootCmd.AddCommand(get)
	rootCmd.AddCommand(add)
	rootCmd.AddCommand(update)
	rootCmd.AddCommand(del)
	rootCmd.AddCommand(list)
	return rootCmd
}

func (c Service) GetEnvironment(name string) (Environment, error) {
	for _, e := range c.Environments {
		if e.Name == name {
			return e, nil
		}
	}
	return Environment{}, NotFoundError
}

func (c Service) AddEnvironment(s Environment) (Service, error) {
	for _, e := range c.Environments {
		if e.Name == s.Name {
			return Service{}, AlreadyExists
		}
	}
	c.Environments = append(c.Environments, s)
	return c, nil
}

func (c Service) DeleteEnvironment(name string) (Service, error) {
	for i, e := range c.Environments {
		if e.Name == name {
			c.Environments = append(c.Environments[:i], c.Environments[i+1:]...)
			return c, nil
		}
	}
	return c, NotFoundError
}

func (c Service) UpdateEnvironment(s Environment) (Service, error) {
	for i, e := range c.Environments {
		if e.Name == s.Name {
			c.Environments[i] = s
			return c, nil
		}
	}
	return c, NotFoundError
}

func (c Service) ListEnvironment() []Environment {
	return c.Environments
}
