// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//nolint
package grpctl

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/joshcarp/grpctl/internal/descriptors"
	"github.com/spf13/cobra"
)

func GetUserCommand(config Config) *cobra.Command {
	var err error
	rootCmd := &cobra.Command{
		Use:   strings.ToLower("User"),
		Short: "configure User",
		Run:   nil,
	}
	something := DefaultUser()
	cobra.CheckErr(err)
	defaultVals, err := descriptors.NewInterfaceDataValue(something)
	flagstorer := make(descriptors.DataMap)
	cobra.CheckErr(err)
	get := &cobra.Command{
		Use:   "get",
		Short: "get a User",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			user, err := config.GetUser(args[0])
			cobra.CheckErr(err)
			fmt.Println(user)
		},
	}
	add := &cobra.Command{
		Use:   "add",
		Short: "add a User",
		Run: func(cmd *cobra.Command, args []string) {
			toJson, err := flagstorer.ToJson()
			cobra.CheckErr(err)
			cobra.CheckErr(json.Unmarshal(toJson, &something))
			config, err = config.AddUser(something)
			cobra.CheckErr(err)
			fmt.Println(config)
			cobra.CheckErr(config.Save())
		},
	}
	del := &cobra.Command{
		Use:   "delete",
		Short: "delete a User",
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			config, err = config.DeleteUser(args[0])
			cobra.CheckErr(err)
			cobra.CheckErr(config.Save())
		},
	}
	update := &cobra.Command{
		Use:   "update",
		Short: "update a User",
		Run: func(cmd *cobra.Command, args []string) {
			src := flagstorer.ToInterfaceMap()
			cobra.CheckErr(err)
			v, ok := flagstorer["name"]
			if !ok {
				cobra.CheckErr(InvalidArg)
			}
			context, err := config.GetUser(v.String())
			dst, err := descriptors.ToInterfaceMap(context)
			cobra.CheckErr(err)
			allmap := descriptors.MergeInterfaceMaps(dst, src)
			cobra.CheckErr(descriptors.MapInterfaceToObject(&context, allmap))
			newcfg, err := config.UpdateUser(context)
			cobra.CheckErr(err)
			cobra.CheckErr(newcfg.Save())
		},
	}
	list := &cobra.Command{
		Use:   "list",
		Short: "list all Users",
		Run: func(cmd *cobra.Command, args []string) {
			for _, val := range config.ListUser() {
				marshal, err := json.Marshal(val)
				cobra.CheckErr(err)
				fmt.Println(string(marshal))
			}
		},
	}
	for key, val := range defaultVals {
		key := key
		val := val
		flagstorer[key] = &descriptors.DataValue{Value: val.Value, Empty: true}
		update.Flags().Var(flagstorer[key], key, "")
		update.RegisterFlagCompletionFunc(key, func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{fmt.Sprintf("%v", val)}, cobra.ShellCompDirectiveDefault
		})
		add.Flags().Var(flagstorer[key], key, "")
		add.RegisterFlagCompletionFunc(key, func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{fmt.Sprintf("%v", val)}, cobra.ShellCompDirectiveDefault
		})
	}
	rootCmd.AddCommand(get)
	rootCmd.AddCommand(add)
	rootCmd.AddCommand(update)
	rootCmd.AddCommand(del)
	rootCmd.AddCommand(list)
	return rootCmd
}

func (c Config) GetUser(name string) (User, error) {
	for _, e := range c.Users {
		if e.Name == name {
			return e, nil
		}
	}
	return User{}, NotFoundError
}

func (c Config) AddUser(s User) (Config, error) {
	for _, e := range c.Users {
		if e.Name == s.Name {
			return Config{}, AlreadyExists
		}
	}
	c.Users = append(c.Users, s)
	return c, nil
}

func (c Config) DeleteUser(name string) (Config, error) {
	for i, e := range c.Users {
		if e.Name == name {
			c.Users = append(c.Users[:i], c.Users[i+1:]...)
			return c, nil
		}
	}
	return c, NotFoundError
}

func (c Config) UpdateUser(s User) (Config, error) {
	for i, e := range c.Users {
		if e.Name == s.Name {
			c.Users[i] = s
			return c, nil
		}
	}
	return c, NotFoundError
}

func (c Config) ListUser() []User {
	return c.Users
}
